version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.env
    volumes:
      - ssc-db-data:/app/data
    restart: unless-stopped
    networks:
      - ssc-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: /api
        VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY-}
        VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN-}
        VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID-}
        VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET-}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID-}
        VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID-}
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ssc-network

volumes:
  ssc-db-data:

networks:
  ssc-network:
    driver: bridge
